ROLE_USER = "USER"
ROLE_MANAGER = "MANAGER"
ROLE_SUPER_ADMIN = "SUPER_ADMIN"

RESERVATION_STATUS_PENDING = "PENDING"
RESERVATION_STATUS_CONFIRMED = "CONFIRMED"
RESERVATION_STATUS_CANCELLED = "CANCELLED"
RESERVATION_STATUS_DONE = "DONE"
RESERVATION_STATUS_NO_SHOW = "NO_SHOW"

FINISHED_RESERVATION_STATUSES = [
    RESERVATION_STATUS_CANCELLED,
    RESERVATION_STATUS_DONE,
    RESERVATION_STATUS_NO_SHOW
]

CREDIT_TRANSACTION_TOP_UP = "TOP_UP"
CREDIT_TRANSACTION_RESERVATION_CHARGE = "RESERVATION_CHARGE"
CREDIT_TRANSACTION_REFUND = "REFUND"
CREDIT_TRANSACTION_MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"
CREDIT_TRANSACTION_LATE_CHECKOUT_PENALTY = "LATE_CHECKOUT_PENALTY"
CREDIT_TRANSACTION_NO_SHOW_PENALTY = "NO_SHOW_PENALTY"
